// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/orzkratos/demokratos/demo2kratos/internal/biz"
	"github.com/orzkratos/demokratos/demo2kratos/internal/conf"
	"github.com/orzkratos/demokratos/demo2kratos/internal/data"
	"github.com/orzkratos/demokratos/demo2kratos/internal/server"
	"github.com/orzkratos/demokratos/demo2kratos/internal/service"
	"github.com/orzkratos/zapkratos"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, zapKratos *zapkratos.ZapKratos) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, zapKratos)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, zapKratos)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, zapKratos)
	greeterService := service.NewGreeterService(greeterUsecase, zapKratos)
	grpcServer := server.NewGRPCServer(confServer, greeterService, zapKratos)
	httpServer := server.NewHTTPServer(confServer, greeterService, zapKratos)
	app := newApp(grpcServer, httpServer, zapKratos)
	return app, func() {
		cleanup()
	}, nil
}
